force-app/main/default/objects/Employee_Associated_with_Mentors__c/Employee_Associated_with_Mentors__c.object-meta.xml
<CustomObject>
    <label>Employee Associated with Mentor</label>
    <nameField>
        <displayFormat>SMI-{000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Associated with Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Associated_with_Mentors__c/fields/SMI_Employee__c.field-meta.xml
<CustomField>
    <fullName>SMI_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SMI Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Associated_with_Mentors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/employeeControllerTest.cls
@isTest
public class employeeControllerTest {
    @isTest
	static void testset(){
    Employee_Associated_with_Mentors__c e = new Employee_Associated_with_Mentors__c (SMI_Employee__c = '0059D000002olJvQAI');
    insert e;
    Test.startTest();
    Employee_Associated_with_Mentors__c testset = [SELECT SMI_Employee__c FROM Employee_Associated_with_Mentors__c LIMIT 1];
    Test.stopTest();
    System.assertEquals(testset, e);
	}
    
    
    @isTest
    static Employee_Associated_with_Mentors__c[] test1(){
        List<Employee_Associated_with_Mentors__c> employeetest = employeeController.searchEmployee('a');
        return employeetest;
    }

}