force-app/main/default/objects/Employee_Associated_with_Mentors__c/Employee_Associated_with_Mentors__c.object-meta.xml
<CustomObject>
    <label>Employee Associated with Mentor</label>
    <nameField>
        <displayFormat>SMI-{000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Associated with Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Associated_with_Mentors__c/fields/Mentor_Name__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Associated_with_Mentors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Associated_with_Mentors__c/fields/Onboarding_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_End_Date__c</fullName>
    <label>Onboarding End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Associated_with_Mentors__c/fields/Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Status__c</fullName>
    <label>Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Associated_with_Mentors__c/fields/SMI_Employee__c.field-meta.xml
<CustomField>
    <fullName>SMI_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SMI Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Associated_with_Mentors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/employeeController.cls
public with sharing class employeeController {

    @AuraEnabled(cacheable=true)
    public static List<sObject> searchEmployee(String searchParam){
        String likeParam = '%' +searchParam+'%';
        String Query = '';
       
        if(searchParam != null){
           Query  = 'Select Name, SMI_Employee__r.Name, Mentor_Name__r.Name, Role__r.Name, Onboarding_End_Date__c, Onboarding_Status__c, Profile__c From Employee_Associated_with_Mentors__c Where SMI_Employee__r.Name Like :likeParam LIMIT 50 ';
        }else{
           Query  = 'Select Name, SMI_Employee__r.Name, Mentor_Name__r.Name, Role__r.Name, Onboarding_End_Date__c, Onboarding_Status__c, Profile__c From Employee_Associated_with_Mentors__c LIMIT 50 '; 
        }
        
        List<SObject> sObjectList = Database.query(Query);
        return sObjectList;
    }

}